### ISSUE TITLE
Lab landing page

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#12]
A landing page for both signed in and signed out states.

**Comment by mcbouslog** [comment]
- [ ] create landing to choose between projects lab (back to PFE) or organizations lab (stay on lab-app)
- [ ] for if not signed-in create component
- [ ] for if signed in edit organizations container if needed, as well as list and list item components

**Comment by amyrebecca** [comment]
@mcbouslog which remaining elements of this are left to be addressed? do you need any help with this?

**Comment by mcbouslog** [comment]
PR #28 adds the organizations owned and collaborate on lists similar to PFE, up to you if you think it would be worthwhile to help with that PR (have a question noted in its comments).

**Comment by srallen** [comment]
Going to close this and open a separate issue for pagination.
