### ISSUE TITLE
Header and footer

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#13]
At first, let's grab the header and footer from PFE. Links will need to be fixed to go back to PFE.

**Comment by mcbouslog** [comment]
- [ ] PR for bare minimum, easiest aspects
- [ ] review and plan Admin functionality
- [ ] implement Admin functionality (to be updated with more details)
- [ ] once `zooniverse-logo` part of Zooniverse-React-Components, remove from pfe-lab and incorporate through import

**Comment by mcbouslog** [comment]
- [ ] PFE layout divided between header and not header (main and footer)
- [ ] PFE conditional classes, using Classnames
- [ ] PFE `<header>` and `<footer>` tags part of layout, then components are within `<div>`'s

**Comment by srallen** [comment]
I'm gonna close this since I think we should start opening up more specific issues about what needs to be finished.
