### ISSUE TITLE
[additional info goes here] showing up on the front page of lab under Orgaization description

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/pfe-lab#188]
Looks like a typo or place holder was left in the landing page on the lab page link sent out to project owners. It looks like someone didn't finish writing the organizations description and left in a placeholder for a link

<img width="1173" alt="Screen Shot 2019-06-24 at 7 59 35 PM" src="https://user-images.githubusercontent.com/753325/60121853-bb14e580-971f-11e9-9498-dc7866dc19b1.png">

**Comment by mcbouslog** [comment]
Thank you for reporting @mschwamb!! Fix should be in soon.
