### ISSUE TITLE
Critical-severity vulnerability in "dompurify" package

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/pfe-lab#208]
See dependabot alert here: https://github.com/zooniverse/pfe-lab/network/alert/package-lock.json/dompurify/open
Note that dependabot wasn't able to automatically create a PR for this "as it doesn't support our dependency files" - I havent seen this error before and I'm unsure of what it means. Investigation necessary, it may be as simple as just needing to manually bump the package version, making sure it builds and pushing it out.

This is a XSS related vulnerability, so it's high priority.

Dompurify has already been updated in PFE based on [conversation in slack #security](https://zooniverse.slack.com/archives/C8MUGEB7V/p1598883427012400), it may be useful to look at the PFE repo for reference.

**Comment by mcbouslog** [comment]
Fixed with #207
