### ISSUE TITLE
high severity security vulnerability: markdown-to-jsx

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/pfe-lab#210]
Relevant security alert: https://github.com/zooniverse/pfe-lab/network/alert/package-lock.json/markdown-to-jsx/open

`markdown-to-jsx` needs to be updated to 6.11.4 or later. This is a XSS issue and should be prioritized. `markdown-to-jsx` converts React markdown to JSX (javascript syntax extension). See more info on [npm page](https://www.npmjs.com/package/markdown-to-jsx).

**Comment by mcbouslog** [comment]
Closed per #213
