### ISSUE TITLE
high severity security vulnerability: decompress

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/pfe-lab#211]
Security alert: https://github.com/zooniverse/pfe-lab/network/alert/package-lock.json/decompress/open

`decompress` needs to be bumped to 4.2.1 or later, prior versions are vulnerable to Arbitrary File Write. `decompress` is used for extracting file archives, see npm page here: https://www.npmjs.com/package/decompress

**Comment by mcbouslog** [comment]
Closed per #213
