### ISSUE TITLE
high severity security vulnerability: bl

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/pfe-lab#212]
Security alert: https://github.com/zooniverse/pfe-lab/network/alert/package-lock.json/bl/open

`bl` (which stands for BufferList) needs to be updated to 1.2.3 or later, previous versions have a vulnerability that can allow malicious users to access uninitialized memory in a buffer. I dont think that `BufferList` functionality is being used in pfe-lab, but it may be being used in one of our dependencies. `bl` provides a `BufferList` class for storing collections of Node Buffers, see more on the npm page: https://www.npmjs.com/package/bl

**Comment by mcbouslog** [comment]
Closed per #213
