### ISSUE TITLE
[Security] The Node build has access to our Azure secrets

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/pfe-lab#263]
Azure secrets here are available to `npm ci` and the build, but they're only needed during the deploy step.
https://github.com/zooniverse/pfe-lab/blob/2f097d8093983488492d49ed20de9b58815b0bd2/.github/workflows/deploy_branch.yml#L21-L29

See PFE for an example of workflows which keep the build and deploy jobs seperate, with Azure secrets only passed to the deploy job.

**Comment by eatyourgreens** [comment]
The danger here is that we don't want to expose secrets to package post-install scripts, if we don't have to.

**Comment by mcbouslog** [comment]
Per #264:

Use the shared workflows. See them here: https://github.com/zooniverse/ci-cd/tree/main/.github/workflows

And an example: https://github.com/zooniverse/pandora/blob/master/.github/workflows/deploy_production.yml
