### ISSUE TITLE
visibility page

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#3]

**Comment by srallen** [comment]
Visibility page will have the interface to request launched approved state. Organizations only have that single state, unlike projects, which is a property on the resource that is either null or a timestamp. If the timestamp is present, it should be visible on this page with the request button disabled. 

Additionally this is where projects will be able to add and remove project links. Basic interface will the a react-select search box searching against the display name of a project and a button to add. Then a list of currently link projects with a remove button. There should be a disclaimer that only launch approved projects will be actually visible on the zooniverse.org organization page.

**Comment by amyrebecca** [comment]
This is in as PR #36
