### ISSUE TITLE
collaborators page

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#4]

**Comment by srallen** [comment]
List of roles for Organizations: https://github.com/zooniverse/Panoptes/blob/7e728059bb894530faa0e28d0ced00e29562ad8a/app/models/organization.rb

**Comment by amyrebecca** [comment]
This one is pretty far along and should make it for Friday.

**Comment by srallen** [comment]
FormContainer component could use some refactoring still and more tests should be written, however basic functionality is in place.
