### ISSUE TITLE
styling clean-up

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/pfe-lab#69]
clean-up styling throughout pfe-lab to mimic PFE Project Builder (feel free to edit the following):
- [x] left side nav
- [x] org list avatars should be square and consistent size
- [x] add Glossary, Policies, Best Practices, Project Builder Talk buttons to org list
- [x] section headers
- [x] collaborators page

**Comment by jelliotartz** [comment]
Moving this to Done for the time being, but feel free to add additional styling issues that get noticed and move back to In Progress.
