### ISSUE TITLE
Setup oauth for pfe-lab

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#8]
Right now the fork from zoo-reduxify is using a client id for a test app. Will need to setup staging and production client ids for this.

Setup trust like wildcam/wildcam lab to make login process as seamless as possible.

**Comment by srallen** [comment]
Created client app in doorkeeper for staging and updated #31. Still need to setup trust levels on the backend like wildcam lab as discussed on slack.

**Comment by amyrebecca** [comment]
The remaining work on this item isn't necessary for the preview, so I'm moving it to the future milestone.

**Comment by srallen** [comment]
This is going to stay open for the production setup

**Comment by mcbouslog** [comment]
I know not requried and technically unrelated, but waiting until lab.zooniverse.org live and will then request - https://github.com/zooniverse/how-to-zooniverse/blob/master/Devops/Avoid%20confirmation%20screen%20for%20trusted%20oauth%20apps.md

**Comment by mcbouslog** [comment]
closing - confirmed pfe-lab has been added as a first party app
