### ISSUE TITLE
Setup deploy task

### ISSUE THREAD

**Issue by srallen** [zooniverse/pfe-lab#9]
Need to setup a staging subdomain and production subdomain to deploy to.

**Comment by srallen** [comment]
Staying open for the production setup as well as deploying to sub-domains for branches like PFE if we want that.

**Comment by mcbouslog** [comment]
for the production setup - what url are we thinking?

currently `zooniverse.org/lab` goes to the current Project Builder, and while the intention is for this app to eventually replace the current `/lab`, that's a ways away, and we'll likely have this app running for organizations in concurrence with the current Project Builder for awhile.

for deploying sub-domains for branches in development, can I copy much of the related current PFE setup?

mentioning @astopy for input

**Comment by astopy** [comment]
I guess we could make it something like lab.zooniverse.org, as long as that won't do anything weird like asking the user to log in a second time.

**Comment by mcbouslog** [comment]
lab.zooniverse.org looks good to me.

so maybe we could do something like:
- production = lab.zooniverse.org
- staging master = master.lab-preview.zooniverse.org
- staging new-feature-branch = new-feature-branch.lab-preview.zooniverse.org

**Comment by astopy** [comment]
Yup, that looks good to me.
